kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-cm
  namespace: openshift-gitops
data:
  # https://github.com/operator-framework/olm-broker/blob/master/vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/installplan_types.go#L51
  resource.customizations.health.operators.coreos.com_InstallPlan: |
    hs = {}
    if obj.status ~= nil then
      if obj.status.phase ~= nil then
        hs.message = obj.status.phase
        if obj.status.phase == "Failed" then
          hs.status = "Degraded"
          return hs
        elseif obj.status.phase == "Complete" then
          hs.status = "Healthy"
          return hs
        end
      end
    end
    hs.status = "Progressing"
    return hs
  resource.customizations.ignoreDifferences.operators.coreos.com_OperatorGroup: |
    jsonPointers:
    - /metadata/annotations/olm.providedAPIs
