kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-cm
  namespace: openshift-gitops
data:
  resource.customizations.health.platform.stackrox.io_Central: |
    hs = {}
    if obj.status ~= nil and obj.status.conditions ~= nil then
      for i, condition in ipairs(obj.status.conditions) do
        if condition.status == "True" and (condition.reason == "InstallSuccessful" or condition.reason =="UpgradeSuccessful") then
          hs.status = "Healthy"
          hs.message = "Install Successful" 
          return hs
        end
      end
    end
    hs.status = "Progressing"
    hs.message = "Waiting for Central to deploy."
    return hs